application: py4ast2
version: 0-0-2
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /favicon.ico
  script: empty_favicon.py

- url: /_ah/queue/deferred
  script: deferred.py 
  login: admin

- url: /admin/.*
  script: admin.py

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*

- url: /__regen
  script: regen.py

- url: /.*
  script: static.py

# builtins:
# - datastore_admin: on

skip_files: |
 ^(.*/)?(
 (#.*#)|
 (.*~)|
 (tmp.*)|
 (.*\.csv)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (bulkloader.*)|
 (themes/coolblue/.*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 (.*\.markdown)|
 (license\.txt)|
 (test\.py)|
 (app_console\.py)|
 (astropython\.wpr)|
 (datastore.*)|
 (.*NOTES.*)|
 (setup.py)
 )$
